//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FiestaReports.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fiesta_EmpStates
    {
        public int Id { get; set; }
        public int EmpId { get; set; }
        public int StateId { get; set; }
        public Nullable<System.DateTime> AssignDate { get; set; }
    
        public virtual Fiesta_Employee Fiesta_Employee { get; set; }
        public virtual Fiesta_State Fiesta_State { get; set; }
    }
}
