//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FiestaReports.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fiesta_EmpStore
    {
        public int EmpId { get; set; }
        public string StoreNo { get; set; }
        public Nullable<System.DateTime> AssignDate { get; set; }
    
        public virtual Fiesta_Employee Fiesta_Employee { get; set; }
        public virtual Fiesta_Store Fiesta_Store { get; set; }
    }
}
