//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FiestaReports.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fiesta_ExcelCompare
    {
        public string DbColName { get; set; }
        public string ExcelColName { get; set; }
        public int ReportId { get; set; }
        public string Datatype { get; set; }
        public bool IsActive { get; set; }
    }
}
