//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FiestaReports.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReportFileUpload
    {
        public int FileId { get; set; }
        public System.Guid FileGUID { get; set; }
        public string FileName { get; set; }
        public string ReportName { get; set; }
        public string UploadedBy { get; set; }
        public System.DateTime UploadDate { get; set; }
        public string Status { get; set; }
    }
}
